language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - travis-ci.org-MinimalWinAPI@hohenegger.eu
    on_success: change
    on_failure: always
env:
  global:
  - secure: CuZ1u9vR2RSSUG1ymKntCR89LD9n/tgFUf9IAUWV8LaCOmztIvo8ZaRqPXfpxxCAjmavZTHU4EyTEpnzqlT3AoysbFErnXO/H9LSRJquZPIqEELGbJEgAOfDc2v0zwlILlWHvA1rV9URmLVc75AKAor/GH7VApT3190VIB1/hiA=
  - secure: Tpqw74RWZnLZPySgEMTspLT9wRYwwvJNGSGPgBT8WCmwcpueygYVdgpm0jbQdPeIa4a8UxBXL6EKUkt12QgH/R7Ae06SEnkVZoy8/eAzH25n0aWGAxG8YoJlq/imgQJDn4ZSMqBjiLErhaRx1HgL/+zeB31OZqvP42vTudb+kyg=
after_success:
- |
  test "${TRAVIS_PULL_REQUEST}" = 'false' && test "${TRAVIS_JDK_VERSION}" = 'oraclejdk8' && sh "$TRAVIS_BUILD_DIR/.travis.credentials.sh"
